# frozen_string_literal: true

# Ensure Active Record encryption keys exist for encrypted attributes.
# In production and development, fall back to a persisted key file if env vars are missing.
# This is needed because Thruster doesn't pass env vars to the Rails subprocess.
return if Rails.env.test?

required_keys = %w[
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
].freeze

missing_keys = required_keys.reject { |key| ENV[key].present? }

if missing_keys.any?
  key_file = Rails.root.join("storage", ".encryption_keys")

  if File.exist?(key_file)
    # Load keys from file (generated by docker-entrypoint)
    File.read(key_file).each_line do |line|
      if line =~ /^export\s+(\w+)="([^"]+)"$/
        ENV[$1] ||= $2
      end
    end
  else
    # Generate new keys and persist them (for development/first run)
    require "securerandom"

    ENV["ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"] = SecureRandom.base64(32)
    ENV["ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"] = SecureRandom.base64(32)
    ENV["ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"] = SecureRandom.base64(32)

    FileUtils.mkdir_p(File.dirname(key_file))
    File.write(
      key_file,
      <<~KEYS
        export ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY="#{ENV["ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"]}"
        export ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY="#{ENV["ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"]}"
        export ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT="#{ENV["ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"]}"
      KEYS
    )
    File.chmod(0o600, key_file)
  end
end
